ALTER TABLE tools ADD COLUMN timeout_ms INT NOT NULL DEFAULT 30000;
ALTER TABLE tools ADD COLUMN max_retries INT NOT NULL DEFAULT 0;
ALTER TABLE tools ADD COLUMN retry_backoff_ms INT NOT NULL DEFAULT 1000;
