ALTER TABLE tools ADD COLUMN cb_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE tools ADD COLUMN cb_error_threshold_pct INT NOT NULL DEFAULT 90;
ALTER TABLE tools ADD COLUMN cb_window_seconds INT NOT NULL DEFAULT 120;
ALTER TABLE tools ADD COLUMN cb_cooldown_seconds INT NOT NULL DEFAULT 60;
